### ISSUE TITLE
Adding "ReplyTo"

### ISSUE THREAD

**Issue by Taidgh** [JacobPimental/SnakeOil#1]
Many spam emails have a different ReplyTo which is the scammers actual email address eg:
From: admin@microsoft.com
ReplyTo: admin.microsoft392093@hotmail.com

Even though the spoofed admin@microsoft.com can often be important the scammers actual email admin.microsoft392093@hotmail.com can be more important.

Even if the "From" is a genuine email such as admin.microsoft39209@hotmail.com, the scammer will have a different ReplyTo as the senders mail will get shut down for spamming.

In practice, the victim of a scam may only research the email address after they have already been emailing the scammer. That is why the ReplyTo is often important.

**Comment by JacobPimental** [comment]
Created branch reply_to (835e3bb5c3e063e1b014ed8d906179b127549c7d) to test this feature.

**Comment by JacobPimental** [comment]
Should be fixed in latest commit 4596c28d3d5710611fb2106d9c5a833b97d3b04d
